stages:
  - checks
  - prepare-build
  - build
  - release

variables:
  SERVICE_NAME: "tools/postgres-db-actions"
  HARBOR_PROJ: devops-services
  TIMESTAMP: ./timestamp.txt
  TAGS: ./tags.txt
  KANIKO_IMAGE: gcr.io/kaniko-project/executor:debug
  DOCKER_CONFIG: /kaniko/.docker/
  APP_NAME: pg_actions

sonarqube-check:
  stage: checks
  image:
    name: sonarsource/sonar-scanner-cli:${SONAR_SCANNER_VERSION}
    entrypoint: [""]
  tags:
    - ivfhq
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" # Defines the location of the analysis task cache
    GIT_DEPTH: "0" # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  allow_failure: true
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
    - if: '$CI_COMMIT_REF_NAME == "main"'

prepare:
  stage: prepare-build
  image:
    name: regcr.ivfuture.uk/gitlab-cicd/prepare:latest
    entrypoint: [""]
  tags:
    - ivfhq
  cache: {}
  before_script:
    - echo "Preparing ..."
    - export CI_PIPELINE_CREATED_AT=$(date +%d%m%Y%H%M)
    - export SHORT_TAG=$(echo $CI_COMMIT_REF_NAME | sed 's/[^a-zA-Z0-9]/-/g' | tr '[:upper:]' '[:lower:]')-latest
    - export LONG_TAG=$(echo $CI_COMMIT_REF_NAME | sed 's/[^a-zA-Z0-9]/-/g' | tr '[:upper:]' '[:lower:]')-$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_CREATED_AT
  script:
    - echo $CI_PIPELINE_CREATED_AT > $TIMESTAMP
    - if [ "$CI_COMMIT_REF_NAME" == "main" ]; then echo "latest" > $TAGS; fi
    - echo $LONG_TAG >> $TAGS
    - echo $SHORT_TAG >> $TAGS
  artifacts:
    paths:
      - $TIMESTAMP
      - $TAGS
  only:
    - branches
    - merge_requests

build:
  stage: build
  dependencies:
    - prepare
  image:
    name: $KANIKO_IMAGE
    entrypoint: [""]
  tags:
    - ivfhq
  interruptible: true
  cache: {}
  before_script:
    - echo "Building ..."
    - path=$(pwd)
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${HARBOR_REPO}\":{\"username\":\"${HARBOR_USERNAME}\",\"password\":\"${HARBOR_PASSWORD}\"}}}" > /kaniko/.docker/config.json
  script:
    - chmod +x devops/prepare.sh && ./devops/prepare.sh
  artifacts:
    paths:
      - $TIMESTAMP
      - $TAGS
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"

build-manual:
  when: manual
  dependencies:
    - prepare
  image:
    name: $KANIKO_IMAGE
    entrypoint: [""]
  tags:
    - ivfhq
  stage: build
  interruptible: true
  cache: {}
  before_script:
    - echo "Building ..."
    - path=$(pwd)
    - export CI_PIPELINE_CREATED_AT=$(date +%d%m%Y%H%M)
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${HARBOR_REPO}\":{\"username\":\"${HARBOR_USERNAME}\",\"password\":\"${HARBOR_PASSWORD}\"}}}" > /kaniko/.docker/config.json
  script:
    - chmod +x devops/prepare.sh && ./devops/prepare.sh
    - echo $CI_PIPELINE_CREATED_AT > $TIMESTAMP
  artifacts:
    paths:
      - $TIMESTAMP
      - $TAGS
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_COMMIT_BRANCH != "dev"

compile:
  stage: build
  dependencies:
    - prepare
  image:
    name: rust:${RUST_VERSION}
  tags:
    - ivfhq
  interruptible: true
  cache: {}
  before_script:
    - echo "Building ..."
    - path=$(pwd)
    - apt update && apt upgrade -y && apt install -y clang lld nala build-essential sudo wget
    - wget -qO - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo gpg --dearmor -o /usr/share/keyrings/postgresql-archive-keyring.gpg
    - echo "deb [signed-by=/usr/share/keyrings/postgresql-archive-keyring.gpg] https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
    - apt update && apt install -y postgresql-client
  script:
    - cargo fetch --locked
    - cargo build --locked --release --target-dir ./target
    - cp target/release/$APP_NAME $CI_PROJECT_DIR
    - mkdir -p artifacts && echo "JOB_ID=$CI_JOB_ID" > artifacts/job.env
  after_script:
    - cat artifacts/job.env # Debug: Check the content of job.env
  artifacts:
    paths:
      - $APP_NAME
      - artifacts/
    expire_in: 1 year
    reports:
      dotenv: artifacts/job.env # Specify the path to the job.env file
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"

create_tag:
  stage: release
  image: alpine:latest # Any lightweight image that has 'curl' and 'jq'
  dependencies:
    - compile # Ensures this job runs after the compile job
  tags:
    - ivfhq
  interruptible: true
  cache: {}
  before_script:
    - echo "Releasing ..."
    - apk update && apk upgrade --no-cache && apk add --no-cache curl jq sed git
  script:
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "$GITLAB_USER_NAME"
    - git remote set-url origin "https://gitlab.com:$GITLAB_TOKEN@gitlab.com/$CI_PROJECT_PATH.git"
    - export RELEASE_VERSION=$(sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml)
    - |
      if git rev-parse "$RELEASE_VERSION" >/dev/null 2>&1; then
        echo "Tag $RELEASE_VERSION already exists. Skipping tag creation."
      else
        git tag -a "$RELEASE_VERSION" -m "Release version $RELEASE_VERSION"
        git push origin "$RELEASE_VERSION"
      fi
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

create_release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  dependencies:
    - compile
  tags:
    - ivfhq
  interruptible: true
  cache: {}
  before_script:
    - echo "Releasing ..."
    - export RELEASE_VERSION=$(sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml)
  script:
    - export JOB_ID=$(cat artifacts/job.env) # Read JOB_ID from job.env
    - echo $JOB_ID
  release:
    name: "Version $RELEASE_VERSION"
    tag_name: "$RELEASE_VERSION"
    description: "Release created using the release-cli. Release '$RELEASE_VERSION'" # Use double quotes for variable interpolation
    assets:
      links:
        - name: "$APP_NAME"
          url: "$CI_SERVER_URL/$CI_PROJECT_PATH/-/jobs/$JOB_ID/artifacts/file/$APP_NAME"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
