stages:
  - checks
  - prepare-build
  - build
  - release

variables:
  SERVICE_NAME: "tools/postgres-db-actions"
  HARBOR_PROJ: devops-services
  TIMESTAMP: ./timestamp.txt
  TAGS: ./tags.txt
  KANIKO_IMAGE: gcr.io/kaniko-project/executor:debug
  DOCKER_CONFIG: /kaniko/.docker/
  APP_NAME: pg_actions

sonarqube-check:
  stage: checks
  image:
    name: sonarsource/sonar-scanner-cli:${SONAR_SCANNER_VERSION}
    entrypoint: [""]
  tags:
    - ivfhq
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" # Defines the location of the analysis task cache
    GIT_DEPTH: "0" # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  allow_failure: true
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
    - if: '$CI_COMMIT_REF_NAME == "main"'

prepare:
  stage: prepare-build
  image:
    name: regcr.ivfuture.uk/gitlab-cicd/prepare:latest
    entrypoint: [""]
  tags:
    - ivfhq
  cache: {}
  before_script:
    - echo "Preparing ..."
    - export CI_PIPELINE_CREATED_AT=$(date +%d%m%Y%H%M)
    - export SHORT_TAG=$(echo $CI_COMMIT_REF_NAME | sed 's/[^a-zA-Z0-9]/-/g' | tr '[:upper:]' '[:lower:]')-latest
    - export LONG_TAG=$(echo $CI_COMMIT_REF_NAME | sed 's/[^a-zA-Z0-9]/-/g' | tr '[:upper:]' '[:lower:]')-$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_CREATED_AT
  script:
    - echo $CI_PIPELINE_CREATED_AT > $TIMESTAMP
    - if [ "$CI_COMMIT_REF_NAME" == "main" ]; then echo "latest" > $TAGS; fi
    - echo $LONG_TAG >> $TAGS
    - echo $SHORT_TAG >> $TAGS
  artifacts:
    paths:
      - $TIMESTAMP
      - $TAGS
  only:
    - branches
    - merge_requests

build:
  stage: build
  dependencies:
    - prepare
  image:
    name: $KANIKO_IMAGE
    entrypoint: [""]
  tags:
    - ivfhq
  interruptible: true
  cache: {}
  before_script:
    - echo "Building ..."
    - path=$(pwd)
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${HARBOR_REPO}\":{\"username\":\"${HARBOR_USERNAME}\",\"password\":\"${HARBOR_PASSWORD}\"}}}" > /kaniko/.docker/config.json
  script:
    - chmod +x devops/prepare.sh && ./devops/prepare.sh
  artifacts:
    paths:
      - $TIMESTAMP
      - $TAGS
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"

build-manual:
  when: manual
  dependencies:
    - prepare
  image:
    name: $KANIKO_IMAGE
    entrypoint: [""]
  tags:
    - ivfhq
  stage: build
  interruptible: true
  cache: {}
  before_script:
    - echo "Building ..."
    - path=$(pwd)
    - export CI_PIPELINE_CREATED_AT=$(date +%d%m%Y%H%M)
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${HARBOR_REPO}\":{\"username\":\"${HARBOR_USERNAME}\",\"password\":\"${HARBOR_PASSWORD}\"}}}" > /kaniko/.docker/config.json
  script:
    - chmod +x devops/prepare.sh && ./devops/prepare.sh
    - echo $CI_PIPELINE_CREATED_AT > $TIMESTAMP
  artifacts:
    paths:
      - $TIMESTAMP
      - $TAGS
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_COMMIT_BRANCH != "dev"

compile:
  stage: build
  dependencies:
    - prepare
  image:
    name: rust:${RUST_VERSION}
  tags:
    - ivfhq
  interruptible: true
  cache: {}
  before_script:
    - echo "Building ..."
    - path=$(pwd)
    - apt update && apt upgrade -y && apt install -y clang lld nala build-essential sudo wget
    - wget -qO - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo gpg --dearmor -o /usr/share/keyrings/postgresql-archive-keyring.gpg
    - echo "deb [signed-by=/usr/share/keyrings/postgresql-archive-keyring.gpg] https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
    - apt update && apt install -y postgresql-client
  script:
    - cargo fetch --locked
    - cargo build --locked --release --target-dir ./target
    - cp target/release/$APP_NAME $CI_PROJECT_DIR
  artifacts:
    paths:
      - $APP_NAME
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"

create_release:
  stage: release
  image: alpine:latest # Any lightweight image that has 'curl' and 'jq'
  dependencies:
    - compile # Ensures this job runs after the compile job
  script:
    - apk update && apk upgrade --no-cache && apk add --no-cache curl jq sed git
    - RELEASE_VERSION=$(sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml)
    - git tag -a "$RELEASE_VERSION" -m "Release version $RELEASE_VERSION"
    - git push origin "$RELEASE_VERSION"
    - |
      curl --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" --upload-file $APP_NAME "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/uploads"
      OUTPUT=$(curl --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/releases")
      URL=$(echo $OUTPUT | jq -r '.url')
      curl --request POST --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" --data "name='Release $CI_COMMIT_REF_NAME'" --data "tag_name='$CI_COMMIT_REF_NAME'" --data "description='Download the new release [here]($URL)'" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/releases"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
