# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  rustfslocal:
    image: rustfs/rustfs:latest
    command: /data
    user: "0:0"
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - postgres_db_actions_network
    volumes:
      - ./data:/data
      - ./certs/public.crt:/opt/certs/rustfs_cert.pem:ro
      - ./certs/private.key:/opt/certs/rustfs_key.pem:ro
      - ./certs/CAs:/opt/certs/CAs:ro
    environment:
      RUSTFS_ACCESS_KEY: rustfsadmin
      RUSTFS_SECRET_KEY: rustfsadmin
      RUSTFS_ADDRESS: ":9000"
      RUSTFS_CONSOLE_ENABLE: "true"
      RUSTFS_TLS_PATH: /opt/certs
  # server:
  #   build:
  #     context: .
  #     target: final
  #   ports:
  #     - 3000:3000
  # The commented out section below is an example of how to define a PostgreSQL
  # database that your application can use. `depends_on` tells Docker Compose to
  # start the database before your application. The `db-data` volume persists the
  # database data between container restarts. The `db-password` secret is used
  # to set the database password. You must create `db/password.txt` and add
  # a password of your choosing to it before running `docker compose up`.
  #     depends_on:
  #       db:
  #         condition: service_healthy
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - postgres_db_actions_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    image: adminer
    # restart: always
    networks:
      - postgres_db_actions_network
    depends_on:
      db:
        condition: service_healthy
        required: true
    ports:
      - 8081:8080

volumes:
  db:

networks:
  postgres_db_actions_network:
    name: ${DOCKER_NETWORK_NAME}
    external: true
