services:
  container:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - devcontainer.env

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    networks:
      - postgres_db_actions_network

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  rustfslocal:
    image: rustfs/rustfs:latest
    command: /data
    user: "0:0"
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - postgres_db_actions_network
    volumes:
      - rustfslocal:/data
      - ../certs/public.crt:/opt/certs/rustfs_cert.pem:ro
      - ../certs/private.key:/opt/certs/rustfs_key.pem:ro
      - ../certs/CAs:/opt/certs/CAs:ro
    env_file:
      - devcontainer.env
  db:
    image: postgres:16-alpine
    env_file:
      - devcontainer.env
    ports:
      - 5432:5432
    networks:
      - postgres_db_actions_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    image: adminer
    # restart: always
    networks:
      - postgres_db_actions_network
    depends_on:
      db:
        condition: service_healthy
        required: true
    ports:
      - 8081:8080

volumes:
  db:
  rustfslocal:

networks:
  postgres_db_actions_network:
