apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-postgres-daily-dev
  namespace: database-backup
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          automountServiceAccountToken: false
          containers:
            - env:
                - name: S3_PREFIX
                  value: postgres-dev/daily
              envFrom:
                - secretRef:
                    name: database-backup-secret-postgres-dev
              args:
                - "backup"
                - "all"
                - "-v"
              image: ghcr.io/cristicriss17g/pg_actions:latest
              imagePullPolicy: Always
              name: backup-postgres-dev
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          imagePullSecrets:
            - name: harbor-ivfuk
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 0 0 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
