apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-backup-secret-postgres-prod
  namespace: database-backup
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: prod/database-backup/database-backup-secret-postgres
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: database-backup-secret-postgres-prod
